### ISSUE TITLE
Problematic Country Codes from Natural Earth Data

### ISSUE THREAD

**Issue by yaph** [yaph/d3-geomap#12]
The SU_A3 country for Palestine is PSX whereas the ISO_A3 code is PSE, so all maps currently created don't display data for Palestine, even if it exists. Using ISO_A3 instead doesn't work either because of wrong/missing values for France and Norway.

See also https://github.com/nvkelso/natural-earth-vector/issues/112

**Comment by bbeekkii** [comment]
There is no Palestine  because it is not a country!
