### ISSUE TITLE
d3.geomap.dependencies.min.js Error

### ISSUE THREAD

**Issue by perrygeo** [yaph/d3-geomap#31]
I get this error in the console (chrome) when using the d3.geomap libraries. I've tried both with the 0.1 release and master, same deal. 

d3.geomap.dependencies.min.js:1 Error: Invalid value for <rect> attribute transform="translate(0, 0"

any ideas?

**Comment by yaph** [comment]
I checked the console output of the example maps on the docs site http://d3-geomap.github.io/map/

This occurrs with choropleth maps and not with plain maps, so far I have no idea why this happens. Does it break your map in any way?

**Comment by yaph** [comment]
I looked a little deeper into the console output, looks like this is an issue in drawLegend().

**Comment by yaph** [comment]
Thanks for reporting!

**Comment by perrygeo** [comment]
@yaph - thanks! Awesome lib btw, great work.

The error didn't break the map in any way ... but it's nice to clear up the console errors anyways. I'll pull master and give it a shot.

**Comment by yaph** [comment]
Thanks and happy mapping!
