### ISSUE TITLE
geomap.min.js broken

### ISSUE THREAD

**Issue by capndave** [yaph/d3-geomap#40]
When using the basic code on your intro page (at http://d3-geomap.github.io/), I get the following error:
TypeError: d is undefined (at 1:20972). Still not able to get a basic map running.

**Comment by yaph** [comment]
Can you post your code to jsfiddle.net or a similar site?

**Comment by capndave** [comment]
Ramiro - I figured out my issue - my mistake. I should have removed the
issue from github. Thanks!

**Comment by yaph** [comment]
OK, never mind.
