### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by szafirov** [yaph/d3-geomap#44]
[This package](https://www.jsdelivr.com/package/npm/d3-geomap) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by szafirov** [comment]
Would like to use the library by importing it as:
`import chloropleth from 'd3-geomap'`

**Comment by yaph** [comment]
I'm not familiar with all the options you have with regards to JS packages and content delivery networks, What file would I need to set as `main` and would this by itself allow the library to be imported the way you intend?

**Comment by szafirov** [comment]
The only way I know would be to do: `export default class Choropleth extends Geomap`, https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export. I am not sure if that is backward compatible with pre ES6 js though.

**Comment by yaph** [comment]
I hope this finally works as expected in version 3.0.0, which I just released.
