### ISSUE TITLE
Custom marker support

### ISSUE THREAD

**Issue by vinayakpatil** [yaph/d3-geomap#48]
![image](https://user-images.githubusercontent.com/3096223/52629979-f46f5600-2ee0-11e9-89d6-92a0b4aa3e31.png)

Is there any way to visualize with custom country markers?

**Comment by yaph** [comment]
There is no built-in way, but you can draw any additional shapes on maps as you like. Here is an example map with cities marked with circles http://maps.ramiro.org/most-murderous-cities-brazil/
