### ISSUE TITLE
Update dependencies to resolve vulnerabilities in d3-color

### ISSUE THREAD

**Issue by boidolr** [yaph/d3-geomap#61]
Right now a vulnerable package (d3-color@1) is pulled in via a transitive dependency.
Is there any chance of getting an updated package with recent dependencies?

I'd like to help out, but can not run the tests, as there seem to be some files missing.

**Comment by yaph** [comment]
Sadly, the dependencies cannot be easily upgraded. There are deprecated dependencies and API changes in newer versions of D3. I just spent quite some time trying to get this to run with newer versions and cannot even built the package any more. Could you build it?

**Comment by boidolr** [comment]
I have a project with this dependency (and not much else) where I had success with using the following in `package.json`:
```
  "overrides": {
    "d3-array": "3",
    "d3-color": "3",
    "d3-fetch": "3",
    "d3-format": "3",
    "d3-geo": "3",
    "d3-selection": "3",
    "d3-transition": "3"
  }
```

**Comment by yaph** [comment]
I upgraded the dependencies, but the code that is built after the upgrade doesn't work any more. I don't see a new release coming any time soon and you're probably better of replacing d3.geomap with a different mapping library.

**Comment by boidolr** [comment]
Ok, understood. Thanks for having a look and trying it out.
