### ISSUE TITLE
Responsive design 

### ISSUE THREAD

**Issue by NitinChakrawarti** [yaph/d3-geomap#63]
landing page of website is not mobile friendly content is not adjusting as per device size,
i can fix that because i have experince in react js along with tailwind css.

screenshot

![Screenshot 2024-10-04 005857](https://github.com/user-attachments/assets/bd04b5d4-98db-4d91-9745-03918c475ab1)

**Comment by yaph** [comment]
Thanks for bringing this up! I'll update the documentation soon with a new version of d3-geomap and will look into this. Neither React nor Tailwind are used.

**Comment by yaph** [comment]
I updated the dependencies on the docs site and it worked in my tests.
![Screenshot from 2024-10-07 23-41-36](https://github.com/user-attachments/assets/2bf0d88e-9e3f-4983-b34b-c0a660ad232c)
